version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env.production
    ports:
      - "${APP_HTTP_PORT}:${APP_HTTP_PORT}"
      - "${APP_GRPC_PORT}:${APP_GRPC_PORT}"