version: "3.9"
services:
  app:
    image: tuannguyensn2001/picket
    env_file:
      - .env
    ports:
      - "${APP_HTTP_PORT}:${APP_HTTP_PORT}"
      - "${APP_GRPC_PORT}:${APP_GRPC_PORT}"
  postgres:
    image: postgres-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./db:/var/lib/postgresql/data